[build-system]
requires = ["uv_build >= 0.9.21, <0.10.0"]
build-backend = "uv_build"

[project]
name = "phd-project" # REQUIRED, is the only field that cannot be marked as dynamic.

version = "0.1.0" # REQUIRED, although can be dynamic

readme = "README.md"

requires-python = ">=3.12"

license = { file = "LICENSE.txt" }

description = "A project for my PhD"

keywords = ["phd", "project", "development"]

authors = [{ name = "Randy White", email = "randy.white.1986@gmail.com" }]

maintainers = [
  { name = "Randy White", email = "randy.white.1986@gmail.com" },
]

dependencies = [
  "httpx",
  "gidgethub[httpx]>4.0.0",
  "django>2.1; os_name != 'nt'",
  "django>2.0; os_name == 'nt'",
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"
#Repository = "https://github.com/me/spam.git"
#"Bug Tracker" = "https://github.com/me/spam/issues"
#Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"
